### ISSUE TITLE
rake redmine:project_priority:seed RAILS_ENV=production --trace

### ISSUE THREAD

**Issue by Falcon30** [nutso/redmine-plugin-project-priority#3]
Hello nutso,

I have tried to install your nice redmine plugin project priority on a running system with several projects.

The command:

rake redmine:plugins:migrate RAILS_ENV=production

works fine for me.

But when I execute the following command:

rake redmine:project_priority:seed RAILS_ENV=production --trace

The command abort with the error messages:
*\* Invoke redmine:project_priority:seed (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:project_priority:seed
Seeding initial project priority values.
rake aborted!
uninitialized constant ProjectPriority

Sorry, I am not so familiar with ruby... 

Any idea how I can install the plugin on a running system  with active projects?

Kind regads,

Falcon30

**Comment by nutso** [comment]
I fixed the seed issue -- turned it into .create instead of.create! allows it to fail gracefully. Can still filter but not display/sort project priority in the issues page
